# -*- coding: utf-8 -*-
"""data_Visualization_titanic.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1g8flU8kFA13jbb3sJtGDd5DBC_chCp08
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

df = sns.load_dataset('titanic')

import plotly.express as px
df

df = sns.load_dataset("titanic")
sns.violinplot(x=df["class"])
print(df)
print(sns.violinplot(x=df["class"]))
plt.show()

